### ISSUE TITLE
feature/frontend

### ISSUE THREAD

**Issue by j-hee-98** [I-Fit/I-Fit#44]
## Description
기능 설명
프론트 최종본

## Todo
- [ ] todo1 : header에서 원데이클래스 제거
- [ ] todo2 : 메인 페이지 carousel-box 디자인 수정
- [ ] todo3 : footer 수정

## etc
기타사항
